controller_manager_ns: controller_manager
controller_list:
  - name: Head_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - HeadYaw
      - HeadPitch
  - name: LeftArm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - LShoulderPitch
      - LShoulderRoll
      - LElbowYaw
      - LElbowRoll
      - LWristYaw
  - name: RightArm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - RShoulderPitch
      - RShoulderRoll
      - RElbowYaw
      - RElbowRoll
      - RWristYaw
  - name: LeftHand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - LHand
  - name: RightHand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - RHand
  - name: Pelvis_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - LHipYawPitch
  - name: LeftLeg_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - LHipRoll
      - LHipPitch
      - LKneePitch
  - name: RightLeg_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - RHipRoll
      - RHipPitch
      - RKneePitch
  - name: LeftAnkle_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - LAnklePitch
  - name: RightAnkle_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - RAnklePitch
  - name: LeftFoot_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - LAnkleRoll
  - name: RightFoot_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - RAnkleRoll



