controller_list:
  - name: fake_Head_controller
    type: $(arg fake_execution_type)
    joints:
      - HeadYaw
      - HeadPitch
  - name: fake_LeftArm_controller
    type: $(arg fake_execution_type)
    joints:
      - LShoulderPitch
      - LShoulderRoll
      - LElbowYaw
      - LElbowRoll
      - LWristYaw
  - name: fake_RightArm_controller
    type: $(arg fake_execution_type)
    joints:
      - RShoulderPitch
      - RShoulderRoll
      - RElbowYaw
      - RElbowRoll
      - RWristYaw
  - name: fake_LeftHand_controller
    type: $(arg fake_execution_type)
    joints:
      - LHand
  - name: fake_RightHand_controller
    type: $(arg fake_execution_type)
    joints:
      - RHand
  - name: fake_Pelvis_controller
    type: $(arg fake_execution_type)
    joints:
      - LHipYawPitch
  - name: fake_LeftLeg_controller
    type: $(arg fake_execution_type)
    joints:
      - LHipRoll
      - LHipPitch
      - LKneePitch
  - name: fake_RightLeg_controller
    type: $(arg fake_execution_type)
    joints:
      - RHipRoll
      - RHipPitch
      - RKneePitch
  - name: fake_LeftAnkle_controller
    type: $(arg fake_execution_type)
    joints:
      - LAnklePitch
  - name: fake_RightAnkle_controller
    type: $(arg fake_execution_type)
    joints:
      - RAnklePitch
  - name: fake_LeftFoot_controller
    type: $(arg fake_execution_type)
    joints:
      - LAnkleRoll
  - name: fake_RightFoot_controller
    type: $(arg fake_execution_type)
    joints:
      - RAnkleRoll
  - name: fake_DualArms_controller
    type: $(arg fake_execution_type)
    joints:
      - LShoulderPitch
      - LShoulderRoll
      - LElbowYaw
      - LElbowRoll
      - LWristYaw
      - RShoulderPitch
      - RShoulderRoll
      - RElbowYaw
      - RElbowRoll
      - RWristYaw
  - name: fake_DualLegs_controller
    type: $(arg fake_execution_type)
    joints:
      - LHipRoll
      - LHipPitch
      - LKneePitch
      - RHipRoll
      - RHipPitch
      - RKneePitch
  - name: fake_DualAnkles_controller
    type: $(arg fake_execution_type)
    joints:
      - LAnklePitch
      - RAnklePitch
  - name: fake_DualLegNfoot_controller
    type: $(arg fake_execution_type)
    joints:
      - LHipRoll
      - LHipPitch
      - LKneePitch
      - LAnklePitch
      - RHipRoll
      - RHipPitch
      - RKneePitch
      - RAnklePitch
  - name: fake_LeftLegNFoot_controller
    type: $(arg fake_execution_type)
    joints:
      - LHipRoll
      - LHipPitch
      - LKneePitch
      - LAnklePitch
  - name: fake_RightLegNFoot_controller
    type: $(arg fake_execution_type)
    joints:
      - RHipRoll
      - RHipPitch
      - RKneePitch
      - RAnklePitch
  - name: fake_LeftArmNRightLeg_controller
    type: $(arg fake_execution_type)
    joints:
      - LShoulderPitch
      - LShoulderRoll
      - LElbowYaw
      - LElbowRoll
      - LWristYaw
      - RHipRoll
      - RHipPitch
      - RKneePitch
  - name: fake_RightArmNLeftLeg_controller
    type: $(arg fake_execution_type)
    joints:
      - LHipRoll
      - LHipPitch
      - LKneePitch
      - RShoulderPitch
      - RShoulderRoll
      - RElbowYaw
      - RElbowRoll
      - RWristYaw

