controller_manager_ns: controller_manager
controller_list:
  - name: Head_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - nao_5/HeadYaw
      - nao_5/HeadPitch
  - name: LeftArm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - nao_5/LShoulderPitch
      - nao_5/LShoulderRoll
      - nao_5/LElbowYaw
      - nao_5/LElbowRoll
      - nao_5/LWristYaw
  - name: RightArm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - nao_5/RShoulderPitch
      - nao_5/RShoulderRoll
      - nao_5/RElbowYaw
      - nao_5/RElbowRoll
      - nao_5/RWristYaw
  - name: LeftHand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - nao_5/LHand
  - name: RightHand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - nao_5/RHand
  - name: Pelvis_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - nao_5/LHipYawPitch
  - name: LeftLeg_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - nao_5/LHipRoll
      - nao_5/LHipPitch
      - nao_5/LKneePitch
  - name: RightLeg_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - nao_5/RHipRoll
      - nao_5/RHipPitch
      - nao_5/RKneePitch
  - name: LeftAnkle_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - nao_5/LAnklePitch
  - name: RightAnkle_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - nao_5/RAnklePitch
  - name: LeftFoot_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - nao_5/LAnkleRoll
  - name: RightFoot_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - nao_5/RAnkleRoll



