controller_manager_ns: controller_manager
controller_list:
  - name: Head_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - nao_4/HeadYaw
      - nao_4/HeadPitch
  - name: LeftArm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - nao_4/LShoulderPitch
      - nao_4/LShoulderRoll
      - nao_4/LElbowYaw
      - nao_4/LElbowRoll
      - nao_4/LWristYaw
  - name: RightArm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - nao_4/RShoulderPitch
      - nao_4/RShoulderRoll
      - nao_4/RElbowYaw
      - nao_4/RElbowRoll
      - nao_4/RWristYaw
  - name: LeftHand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - nao_4/LHand
  - name: RightHand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - nao_4/RHand
  - name: Pelvis_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - nao_4/LHipYawPitch
  - name: LeftLeg_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - nao_4/LHipRoll
      - nao_4/LHipPitch
      - nao_4/LKneePitch
  - name: RightLeg_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - nao_4/RHipRoll
      - nao_4/RHipPitch
      - nao_4/RKneePitch
  - name: LeftAnkle_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - nao_4/LAnklePitch
  - name: RightAnkle_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - nao_4/RAnklePitch
  - name: LeftFoot_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - nao_4/LAnkleRoll
  - name: RightFoot_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - nao_4/RAnkleRoll



