controller_manager_ns: controller_manager
controller_list:
  - name: Head_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - nao_6/HeadYaw
      - nao_6/HeadPitch
  - name: LeftArm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - nao_6/LShoulderPitch
      - nao_6/LShoulderRoll
      - nao_6/LElbowYaw
      - nao_6/LElbowRoll
      - nao_6/LWristYaw
  - name: RightArm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - nao_6/RShoulderPitch
      - nao_6/RShoulderRoll
      - nao_6/RElbowYaw
      - nao_6/RElbowRoll
      - nao_6/RWristYaw
  - name: LeftHand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - nao_6/LHand
  - name: RightHand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - nao_6/RHand
  - name: Pelvis_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - nao_6/LHipYawPitch
  - name: LeftLeg_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - nao_6/LHipRoll
      - nao_6/LHipPitch
      - nao_6/LKneePitch
  - name: RightLeg_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - nao_6/RHipRoll
      - nao_6/RHipPitch
      - nao_6/RKneePitch
  - name: LeftAnkle_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - nao_6/LAnklePitch
  - name: RightAnkle_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - nao_6/RAnklePitch
  - name: LeftFoot_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - nao_6/LAnkleRoll
  - name: RightFoot_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - nao_6/RAnkleRoll



