  # Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  

  # Controllers ------------------------------------------------
Head_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_4/HeadYaw
    - nao_4/HeadPitch
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0

LeftArm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_4/LShoulderPitch
    - nao_4/LShoulderRoll
    - nao_4/LElbowYaw
    - nao_4/LElbowRoll
    - nao_4/LWristYaw
  constraints:
    goal_time: 0.8
    stopped_velocity_tolerance: 0
    nao_4/LShoulderPitch: {trajectory: 0.1, goal: 0.1}
    nao_4/LShoulderRoll: {trajectory: 0.3, goal: 0.2}
    nao_4/LElbowYaw: {trajectory: 0.2, goal: 0.1}
    nao_4/LElbowRoll: {trajectory: 0.3, goal: 0.1}
    nao_4/LWristYaw: {trajectory: 0.1, goal: 0.1}

RightArm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_4/RShoulderPitch
    - nao_4/RShoulderRoll
    - nao_4/RElbowYaw
    - nao_4/RElbowRoll
    - nao_4/RWristYaw
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_4/RShoulderPitch: {trajectory: 0.3, goal: 0.1}
    nao_4/RShoulderRoll: {trajectory: 0.3, goal: 0.2}
    nao_4/RElbowYaw: {trajectory: 0.3, goal: 0.1}
    nao_4/RElbowRoll: {trajectory: 0.5, goal: 0.2}
    nao_4/RWristYaw: {trajectory: 0.5, goal: 0.2}

LeftHand_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_4/LHand
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_4/LHand: {trajectory: 0.3, goal: 0.1}

RightHand_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_4/RHand
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_4/RHand: {trajectory: 0.3, goal: 0.1}

Pelvis_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_4/LHipYawPitch
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_4/LHipYawPitch: {trajectory: 0.3, goal: 0.1}

LeftLeg_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_4/LHipRoll
    - nao_4/LHipPitch
    - nao_4/LKneePitch
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_4/LHipRoll: {trajectory: 0.3, goal: 0.1}
    nao_4/LHipPitch: {trajectory: 0.3, goal: 0.1}
    nao_4/LKneePitch: {trajectory: 0.3, goal: 0.1}

RightLeg_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_4/RHipRoll
    - nao_4/RHipPitch
    - nao_4/RKneePitch
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_4/RHipRoll: {trajectory: 0.3, goal: 0.1}
    nao_4/RHipPitch: {trajectory: 0.3, goal: 0.1}
    nao_4/RKneePitch: {trajectory: 0.3, goal: 0.1}

LeftAnkle_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_4/LAnklePitch
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_4/LAnklePitch: {trajectory: 0.3, goal: 0.1}

RightAnkle_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_4/RAnklePitch
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_4/RAnklePitch: {trajectory: 0.3, goal: 0.1}

LeftFoot_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_4/LAnkleRoll
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_4/LAnkleRoll: {trajectory: 0.3, goal: 0.1}

RightFoot_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_4/RAnkleRoll
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_4/RAnkleRoll: {trajectory: 0.3, goal: 0.1}

LeftWheels_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
   - nao_4/left_wheel_joint_l
   - nao_4/left_wheel_joint_r
   - nao_4/front_left_wheel_joint_l
   - nao_4/front_left_wheel_joint_l

RightWheels_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
   - nao_4/right_wheel_joint_l
   - nao_4/right_wheel_joint_r
   - nao_4/front_right_wheel_joint_l
   - nao_4/front_right_wheel_joint_r


gazebo_ros_control:
    pid_gains:
      nao_4/HeadYaw: 
          p: 1000.0
          i: 100.0
          d: 1.0

      nao_4/HeadPitch:
          p: 1000.0
          i: 100.0
          d: 1.0

      nao_4/LShoulderPitch:
          p: 80.0
          i: 4.0
          d: 2.0

      nao_4/LElbowYaw:
          p: 100.0
          i: 100.0
          d: 0.0

      nao_4/LElbowRoll:
          p: 100.0
          i: 100.0
          d: 0.0

      nao_4/LShoulderRoll:
          p: 50.0
          i: 5.0
          d: 0.7

      nao_4/LWristYaw:
          p: 1.0
          i: 0.13
          d: 0.01

      nao_4/LHand:
          p: 0.0
          i: 0.0
          d: 0.0

      nao_4/RShoulderPitch:
          p: 80.0
          i: 4.0
          d: 2.0

      nao_4/RElbowYaw:
          p: 100.0
          i: 100.0
          d: 0.0

      nao_4/RElbowRoll:
          p: 100.0
          i: 100.0
          d: 0.0

      nao_4/RShoulderRoll:
          p: 50.0
          i: 5.0
          d: 0.7

      nao_4/RWristYaw:
          p: 1.0
          i: 0.13
          d: 0.01

      nao_4/RHand:
          p: 0.0
          i: 0.0
          d: 0.0

      nao_4/LHipYawPitch:
          p: 500.0
          i: 0.0
          d: 0.1

      nao_4/LHipRoll:
          p: 500.0
          i: 0.0
          d: 0.1

      nao_4/LHipPitch:
          p: 500.0
          i: 0.0
          d: 0.1

      nao_4/LKneePitch:
          p: 500.0
          i: 0.0
          d: 0.0

      nao_4/LAnklePitch:
          p: 500.0
          i: 0.0
          d: 0.0

      nao_4/LAnkleRoll:
          p: 500.0
          i: 0.0
          d: 0.0

      nao_4/left_wheel_joint_l:
          p: 0.0
          i: 0.0
          d: 0.0

      nao_4/left_wheel_joint_r:
          p: 0.0
          i: 0.0
          d: 0.0
        
      nao_4/right_wheel_joint_l:
          p: 0.0
          i: 0.0
          d: 0.0
        
      nao_4/right_wheel_joint_r:
          p: 0.0
          i: 0.0
          d: 0.0

      nao_4/RHipYawPitch:
          p: 500.0
          i: 0.0
          d: 0.1

      nao_4/RHipRoll:
          p: 500.0
          i: 0.0
          d: 0.1

      nao_4/RHipPitch:
          p: 500.0
          i: 0.0
          d: 0.1

      nao_4/RKneePitch:
          p: 500.0
          i: 0.0
          d: 0.0

      nao_4/RAnklePitch:
          p: 500.0
          i: 0.0
          d: 0.0

      nao_4/RAnkleRoll:
          p: 500.0
          i: 0.0
          d: 0.0
        
      nao_4/front_left_wheel_joint_l:
          p: 0.0
          i: 0.0
          d: 0.0

      nao_4/front_left_wheel_joint_r:
          p: 0.0
          i: 0.0
          d: 0.0

      nao_4/front_right_wheel_joint_l:
          p: 0.0
          i: 0.0
          d: 0.0

      nao_4/front_right_wheel_joint_r:
          p: 0.0
          i: 0.0
          d: 0.0
