  # Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  

  # Controllers ------------------------------------------------
Head_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_6/HeadYaw
    - nao_6/HeadPitch
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0

LeftArm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_6/LShoulderPitch
    - nao_6/LShoulderRoll
    - nao_6/LElbowYaw
    - nao_6/LElbowRoll
    - nao_6/LWristYaw
  constraints:
    goal_time: 0.8
    stopped_velocity_tolerance: 0
    nao_6/LShoulderPitch: {trajectory: 0.1, goal: 0.1}
    nao_6/LShoulderRoll: {trajectory: 0.3, goal: 0.2}
    nao_6/LElbowYaw: {trajectory: 0.2, goal: 0.1}
    nao_6/LElbowRoll: {trajectory: 0.3, goal: 0.1}
    nao_6/LWristYaw: {trajectory: 0.1, goal: 0.1}

RightArm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_6/RShoulderPitch
    - nao_6/RShoulderRoll
    - nao_6/RElbowYaw
    - nao_6/RElbowRoll
    - nao_6/RWristYaw
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_6/RShoulderPitch: {trajectory: 0.3, goal: 0.1}
    nao_6/RShoulderRoll: {trajectory: 0.3, goal: 0.2}
    nao_6/RElbowYaw: {trajectory: 0.3, goal: 0.1}
    nao_6/RElbowRoll: {trajectory: 0.5, goal: 0.2}
    nao_6/RWristYaw: {trajectory: 0.5, goal: 0.2}

LeftHand_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_6/LHand
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_6/LHand: {trajectory: 0.3, goal: 0.1}

RightHand_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_6/RHand
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_6/RHand: {trajectory: 0.3, goal: 0.1}

Pelvis_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_6/LHipYawPitch
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_6/LHipYawPitch: {trajectory: 0.3, goal: 0.1}

LeftLeg_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_6/LHipRoll
    - nao_6/LHipPitch
    - nao_6/LKneePitch
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_6/LHipRoll: {trajectory: 0.3, goal: 0.1}
    nao_6/LHipPitch: {trajectory: 0.3, goal: 0.1}
    nao_6/LKneePitch: {trajectory: 0.3, goal: 0.1}

RightLeg_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_6/RHipRoll
    - nao_6/RHipPitch
    - nao_6/RKneePitch
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_6/RHipRoll: {trajectory: 0.3, goal: 0.1}
    nao_6/RHipPitch: {trajectory: 0.3, goal: 0.1}
    nao_6/RKneePitch: {trajectory: 0.3, goal: 0.1}

LeftAnkle_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_6/LAnklePitch
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_6/LAnklePitch: {trajectory: 0.3, goal: 0.1}

RightAnkle_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_6/RAnklePitch
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_6/RAnklePitch: {trajectory: 0.3, goal: 0.1}

LeftFoot_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_6/LAnkleRoll
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_6/LAnkleRoll: {trajectory: 0.3, goal: 0.1}

RightFoot_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_6/RAnkleRoll
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_6/RAnkleRoll: {trajectory: 0.3, goal: 0.1}

LeftWheels_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
   - nao_6/left_wheel_joint_l
   - nao_6/left_wheel_joint_r
   - nao_6/front_left_wheel_joint_l
   - nao_6/front_left_wheel_joint_l

RightWheels_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
   - nao_6/right_wheel_joint_l
   - nao_6/right_wheel_joint_r
   - nao_6/front_right_wheel_joint_l
   - nao_6/front_right_wheel_joint_r


gazebo_ros_control:
    pid_gains:
      nao_6/HeadYaw: 
          p: 1000.0
          i: 100.0
          d: 1.0

      nao_6/HeadPitch:
          p: 1000.0
          i: 100.0
          d: 1.0

      nao_6/LShoulderPitch:
          p: 80.0
          i: 4.0
          d: 2.0

      nao_6/LElbowYaw:
          p: 100.0
          i: 100.0
          d: 0.0

      nao_6/LElbowRoll:
          p: 100.0
          i: 100.0
          d: 0.0

      nao_6/LShoulderRoll:
          p: 50.0
          i: 5.0
          d: 0.7

      nao_6/LWristYaw:
          p: 1.0
          i: 0.13
          d: 0.01

      nao_6/LHand:
          p: 0.0
          i: 0.0
          d: 0.0

      nao_6/RShoulderPitch:
          p: 80.0
          i: 4.0
          d: 2.0

      nao_6/RElbowYaw:
          p: 100.0
          i: 100.0
          d: 0.0

      nao_6/RElbowRoll:
          p: 100.0
          i: 100.0
          d: 0.0

      nao_6/RShoulderRoll:
          p: 50.0
          i: 5.0
          d: 0.7

      nao_6/RWristYaw:
          p: 1.0
          i: 0.13
          d: 0.01

      nao_6/RHand:
          p: 0.0
          i: 0.0
          d: 0.0

      nao_6/LHipYawPitch:
          p: 500.0
          i: 0.0
          d: 0.1

      nao_6/LHipRoll:
          p: 500.0
          i: 0.0
          d: 0.1

      nao_6/LHipPitch:
          p: 500.0
          i: 0.0
          d: 0.1

      nao_6/LKneePitch:
          p: 500.0
          i: 0.0
          d: 0.0

      nao_6/LAnklePitch:
          p: 500.0
          i: 0.0
          d: 0.0

      nao_6/LAnkleRoll:
          p: 500.0
          i: 0.0
          d: 0.0

      nao_6/left_wheel_joint_l:
          p: 0.0
          i: 0.0
          d: 0.0

      nao_6/left_wheel_joint_r:
          p: 0.0
          i: 0.0
          d: 0.0
        
      nao_6/right_wheel_joint_l:
          p: 0.0
          i: 0.0
          d: 0.0
        
      nao_6/right_wheel_joint_r:
          p: 0.0
          i: 0.0
          d: 0.0

      nao_6/RHipYawPitch:
          p: 500.0
          i: 0.0
          d: 0.1

      nao_6/RHipRoll:
          p: 500.0
          i: 0.0
          d: 0.1

      nao_6/RHipPitch:
          p: 500.0
          i: 0.0
          d: 0.1

      nao_6/RKneePitch:
          p: 500.0
          i: 0.0
          d: 0.0

      nao_6/RAnklePitch:
          p: 500.0
          i: 0.0
          d: 0.0

      nao_6/RAnkleRoll:
          p: 500.0
          i: 0.0
          d: 0.0
        
      nao_6/front_left_wheel_joint_l:
          p: 0.0
          i: 0.0
          d: 0.0

      nao_6/front_left_wheel_joint_r:
          p: 0.0
          i: 0.0
          d: 0.0

      nao_6/front_right_wheel_joint_l:
          p: 0.0
          i: 0.0
          d: 0.0

      nao_6/front_right_wheel_joint_r:
          p: 0.0
          i: 0.0
          d: 0.0
