  # Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  

  # Controllers ------------------------------------------------
Head_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_7/HeadYaw
    - nao_7/HeadPitch
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0

LeftArm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_7/LShoulderPitch
    - nao_7/LShoulderRoll
    - nao_7/LElbowYaw
    - nao_7/LElbowRoll
    - nao_7/LWristYaw
  constraints:
    goal_time: 0.8
    stopped_velocity_tolerance: 0
    nao_7/LShoulderPitch: {trajectory: 0.1, goal: 0.1}
    nao_7/LShoulderRoll: {trajectory: 0.3, goal: 0.2}
    nao_7/LElbowYaw: {trajectory: 0.2, goal: 0.1}
    nao_7/LElbowRoll: {trajectory: 0.3, goal: 0.1}
    nao_7/LWristYaw: {trajectory: 0.1, goal: 0.1}

RightArm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_7/RShoulderPitch
    - nao_7/RShoulderRoll
    - nao_7/RElbowYaw
    - nao_7/RElbowRoll
    - nao_7/RWristYaw
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_7/RShoulderPitch: {trajectory: 0.3, goal: 0.1}
    nao_7/RShoulderRoll: {trajectory: 0.3, goal: 0.2}
    nao_7/RElbowYaw: {trajectory: 0.3, goal: 0.1}
    nao_7/RElbowRoll: {trajectory: 0.5, goal: 0.2}
    nao_7/RWristYaw: {trajectory: 0.5, goal: 0.2}

LeftHand_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_7/LHand
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_7/LHand: {trajectory: 0.3, goal: 0.1}

RightHand_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_7/RHand
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_7/RHand: {trajectory: 0.3, goal: 0.1}

Pelvis_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_7/LHipYawPitch
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_7/LHipYawPitch: {trajectory: 0.3, goal: 0.1}

LeftLeg_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_7/LHipRoll
    - nao_7/LHipPitch
    - nao_7/LKneePitch
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_7/LHipRoll: {trajectory: 0.3, goal: 0.1}
    nao_7/LHipPitch: {trajectory: 0.3, goal: 0.1}
    nao_7/LKneePitch: {trajectory: 0.3, goal: 0.1}

RightLeg_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_7/RHipRoll
    - nao_7/RHipPitch
    - nao_7/RKneePitch
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_7/RHipRoll: {trajectory: 0.3, goal: 0.1}
    nao_7/RHipPitch: {trajectory: 0.3, goal: 0.1}
    nao_7/RKneePitch: {trajectory: 0.3, goal: 0.1}

LeftAnkle_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_7/LAnklePitch
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_7/LAnklePitch: {trajectory: 0.3, goal: 0.1}

RightAnkle_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_7/RAnklePitch
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_7/RAnklePitch: {trajectory: 0.3, goal: 0.1}

LeftFoot_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_7/LAnkleRoll
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_7/LAnkleRoll: {trajectory: 0.3, goal: 0.1}

RightFoot_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_7/RAnkleRoll
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_7/RAnkleRoll: {trajectory: 0.3, goal: 0.1}

LeftWheels_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
   - nao_7/left_wheel_joint_l
   - nao_7/left_wheel_joint_r
   - nao_7/front_left_wheel_joint_l
   - nao_7/front_left_wheel_joint_l

RightWheels_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
   - nao_7/right_wheel_joint_l
   - nao_7/right_wheel_joint_r
   - nao_7/front_right_wheel_joint_l
   - nao_7/front_right_wheel_joint_r


gazebo_ros_control:
    pid_gains:
      nao_7/HeadYaw: 
          p: 1000.0
          i: 100.0
          d: 1.0

      nao_7/HeadPitch:
          p: 1000.0
          i: 100.0
          d: 1.0

      nao_7/LShoulderPitch:
          p: 80.0
          i: 4.0
          d: 2.0

      nao_7/LElbowYaw:
          p: 100.0
          i: 100.0
          d: 0.0

      nao_7/LElbowRoll:
          p: 100.0
          i: 100.0
          d: 0.0

      nao_7/LShoulderRoll:
          p: 50.0
          i: 5.0
          d: 0.7

      nao_7/LWristYaw:
          p: 1.0
          i: 0.13
          d: 0.01

      nao_7/LHand:
          p: 0.0
          i: 0.0
          d: 0.0

      nao_7/RShoulderPitch:
          p: 80.0
          i: 4.0
          d: 2.0

      nao_7/RElbowYaw:
          p: 100.0
          i: 100.0
          d: 0.0

      nao_7/RElbowRoll:
          p: 100.0
          i: 100.0
          d: 0.0

      nao_7/RShoulderRoll:
          p: 50.0
          i: 5.0
          d: 0.7

      nao_7/RWristYaw:
          p: 1.0
          i: 0.13
          d: 0.01

      nao_7/RHand:
          p: 0.0
          i: 0.0
          d: 0.0

      nao_7/LHipYawPitch:
          p: 500.0
          i: 0.0
          d: 0.1

      nao_7/LHipRoll:
          p: 500.0
          i: 0.0
          d: 0.1

      nao_7/LHipPitch:
          p: 500.0
          i: 0.0
          d: 0.1

      nao_7/LKneePitch:
          p: 500.0
          i: 0.0
          d: 0.0

      nao_7/LAnklePitch:
          p: 500.0
          i: 0.0
          d: 0.0

      nao_7/LAnkleRoll:
          p: 500.0
          i: 0.0
          d: 0.0

      nao_7/left_wheel_joint_l:
          p: 0.0
          i: 0.0
          d: 0.0

      nao_7/left_wheel_joint_r:
          p: 0.0
          i: 0.0
          d: 0.0
        
      nao_7/right_wheel_joint_l:
          p: 0.0
          i: 0.0
          d: 0.0
        
      nao_7/right_wheel_joint_r:
          p: 0.0
          i: 0.0
          d: 0.0

      nao_7/RHipYawPitch:
          p: 500.0
          i: 0.0
          d: 0.1

      nao_7/RHipRoll:
          p: 500.0
          i: 0.0
          d: 0.1

      nao_7/RHipPitch:
          p: 500.0
          i: 0.0
          d: 0.1

      nao_7/RKneePitch:
          p: 500.0
          i: 0.0
          d: 0.0

      nao_7/RAnklePitch:
          p: 500.0
          i: 0.0
          d: 0.0

      nao_7/RAnkleRoll:
          p: 500.0
          i: 0.0
          d: 0.0
        
      nao_7/front_left_wheel_joint_l:
          p: 0.0
          i: 0.0
          d: 0.0

      nao_7/front_left_wheel_joint_r:
          p: 0.0
          i: 0.0
          d: 0.0

      nao_7/front_right_wheel_joint_l:
          p: 0.0
          i: 0.0
          d: 0.0

      nao_7/front_right_wheel_joint_r:
          p: 0.0
          i: 0.0
          d: 0.0
