  # Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  

  # Controllers ------------------------------------------------
Head_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_3/HeadYaw
    - nao_3/HeadPitch
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0

LeftArm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_3/LShoulderPitch
    - nao_3/LShoulderRoll
    - nao_3/LElbowYaw
    - nao_3/LElbowRoll
    - nao_3/LWristYaw
  constraints:
    goal_time: 0.8
    stopped_velocity_tolerance: 0
    nao_3/LShoulderPitch: {trajectory: 0.1, goal: 0.1}
    nao_3/LShoulderRoll: {trajectory: 0.3, goal: 0.2}
    nao_3/LElbowYaw: {trajectory: 0.2, goal: 0.1}
    nao_3/LElbowRoll: {trajectory: 0.3, goal: 0.1}
    nao_3/LWristYaw: {trajectory: 0.1, goal: 0.1}

RightArm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_3/RShoulderPitch
    - nao_3/RShoulderRoll
    - nao_3/RElbowYaw
    - nao_3/RElbowRoll
    - nao_3/RWristYaw
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_3/RShoulderPitch: {trajectory: 0.3, goal: 0.1}
    nao_3/RShoulderRoll: {trajectory: 0.3, goal: 0.2}
    nao_3/RElbowYaw: {trajectory: 0.3, goal: 0.1}
    nao_3/RElbowRoll: {trajectory: 0.5, goal: 0.2}
    nao_3/RWristYaw: {trajectory: 0.5, goal: 0.2}

LeftHand_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_3/LHand
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_3/LHand: {trajectory: 0.3, goal: 0.1}

RightHand_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_3/RHand
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_3/RHand: {trajectory: 0.3, goal: 0.1}

Pelvis_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_3/LHipYawPitch
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_3/LHipYawPitch: {trajectory: 0.3, goal: 0.1}

LeftLeg_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_3/LHipRoll
    - nao_3/LHipPitch
    - nao_3/LKneePitch
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_3/LHipRoll: {trajectory: 0.3, goal: 0.1}
    nao_3/LHipPitch: {trajectory: 0.3, goal: 0.1}
    nao_3/LKneePitch: {trajectory: 0.3, goal: 0.1}

RightLeg_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_3/RHipRoll
    - nao_3/RHipPitch
    - nao_3/RKneePitch
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_3/RHipRoll: {trajectory: 0.3, goal: 0.1}
    nao_3/RHipPitch: {trajectory: 0.3, goal: 0.1}
    nao_3/RKneePitch: {trajectory: 0.3, goal: 0.1}

LeftAnkle_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_3/LAnklePitch
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_3/LAnklePitch: {trajectory: 0.3, goal: 0.1}

RightAnkle_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_3/RAnklePitch
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_3/RAnklePitch: {trajectory: 0.3, goal: 0.1}

LeftFoot_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_3/LAnkleRoll
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_3/LAnkleRoll: {trajectory: 0.3, goal: 0.1}

RightFoot_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_3/RAnkleRoll
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_3/RAnkleRoll: {trajectory: 0.3, goal: 0.1}

LeftWheels_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
   - nao_3/left_wheel_joint_l
   - nao_3/left_wheel_joint_r
   - nao_3/front_left_wheel_joint_l
   - nao_3/front_left_wheel_joint_l

RightWheels_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
   - nao_3/right_wheel_joint_l
   - nao_3/right_wheel_joint_r
   - nao_3/front_right_wheel_joint_l
   - nao_3/front_right_wheel_joint_r


gazebo_ros_control:
    pid_gains:
      nao_3/HeadYaw: 
          p: 1000.0
          i: 100.0
          d: 1.0

      nao_3/HeadPitch:
          p: 1000.0
          i: 100.0
          d: 1.0

      nao_3/LShoulderPitch:
          p: 80.0
          i: 4.0
          d: 2.0

      nao_3/LElbowYaw:
          p: 100.0
          i: 100.0
          d: 0.0

      nao_3/LElbowRoll:
          p: 100.0
          i: 100.0
          d: 0.0

      nao_3/LShoulderRoll:
          p: 50.0
          i: 5.0
          d: 0.7

      nao_3/LWristYaw:
          p: 1.0
          i: 0.13
          d: 0.01

      nao_3/LHand:
          p: 0.0
          i: 0.0
          d: 0.0

      nao_3/RShoulderPitch:
          p: 80.0
          i: 4.0
          d: 2.0

      nao_3/RElbowYaw:
          p: 100.0
          i: 100.0
          d: 0.0

      nao_3/RElbowRoll:
          p: 100.0
          i: 100.0
          d: 0.0

      nao_3/RShoulderRoll:
          p: 50.0
          i: 5.0
          d: 0.7

      nao_3/RWristYaw:
          p: 1.0
          i: 0.13
          d: 0.01

      nao_3/RHand:
          p: 0.0
          i: 0.0
          d: 0.0

      nao_3/LHipYawPitch:
          p: 500.0
          i: 0.0
          d: 0.1

      nao_3/LHipRoll:
          p: 500.0
          i: 0.0
          d: 0.1

      nao_3/LHipPitch:
          p: 500.0
          i: 0.0
          d: 0.1

      nao_3/LKneePitch:
          p: 500.0
          i: 0.0
          d: 0.0

      nao_3/LAnklePitch:
          p: 500.0
          i: 0.0
          d: 0.0

      nao_3/LAnkleRoll:
          p: 500.0
          i: 0.0
          d: 0.0

      nao_3/left_wheel_joint_l:
          p: 0.0
          i: 0.0
          d: 0.0

      nao_3/left_wheel_joint_r:
          p: 0.0
          i: 0.0
          d: 0.0
        
      nao_3/right_wheel_joint_l:
          p: 0.0
          i: 0.0
          d: 0.0
        
      nao_3/right_wheel_joint_r:
          p: 0.0
          i: 0.0
          d: 0.0

      nao_3/RHipYawPitch:
          p: 500.0
          i: 0.0
          d: 0.1

      nao_3/RHipRoll:
          p: 500.0
          i: 0.0
          d: 0.1

      nao_3/RHipPitch:
          p: 500.0
          i: 0.0
          d: 0.1

      nao_3/RKneePitch:
          p: 500.0
          i: 0.0
          d: 0.0

      nao_3/RAnklePitch:
          p: 500.0
          i: 0.0
          d: 0.0

      nao_3/RAnkleRoll:
          p: 500.0
          i: 0.0
          d: 0.0
        
      nao_3/front_left_wheel_joint_l:
          p: 0.0
          i: 0.0
          d: 0.0

      nao_3/front_left_wheel_joint_r:
          p: 0.0
          i: 0.0
          d: 0.0

      nao_3/front_right_wheel_joint_l:
          p: 0.0
          i: 0.0
          d: 0.0

      nao_3/front_right_wheel_joint_r:
          p: 0.0
          i: 0.0
          d: 0.0
