  # Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  

  # Controllers ------------------------------------------------
Head_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_5/HeadYaw
    - nao_5/HeadPitch
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0

LeftArm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_5/LShoulderPitch
    - nao_5/LShoulderRoll
    - nao_5/LElbowYaw
    - nao_5/LElbowRoll
    - nao_5/LWristYaw
  constraints:
    goal_time: 0.8
    stopped_velocity_tolerance: 0
    nao_5/LShoulderPitch: {trajectory: 0.1, goal: 0.1}
    nao_5/LShoulderRoll: {trajectory: 0.3, goal: 0.2}
    nao_5/LElbowYaw: {trajectory: 0.2, goal: 0.1}
    nao_5/LElbowRoll: {trajectory: 0.3, goal: 0.1}
    nao_5/LWristYaw: {trajectory: 0.1, goal: 0.1}

RightArm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_5/RShoulderPitch
    - nao_5/RShoulderRoll
    - nao_5/RElbowYaw
    - nao_5/RElbowRoll
    - nao_5/RWristYaw
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_5/RShoulderPitch: {trajectory: 0.3, goal: 0.1}
    nao_5/RShoulderRoll: {trajectory: 0.3, goal: 0.2}
    nao_5/RElbowYaw: {trajectory: 0.3, goal: 0.1}
    nao_5/RElbowRoll: {trajectory: 0.5, goal: 0.2}
    nao_5/RWristYaw: {trajectory: 0.5, goal: 0.2}

LeftHand_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_5/LHand
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_5/LHand: {trajectory: 0.3, goal: 0.1}

RightHand_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_5/RHand
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_5/RHand: {trajectory: 0.3, goal: 0.1}

Pelvis_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_5/LHipYawPitch
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_5/LHipYawPitch: {trajectory: 0.3, goal: 0.1}

LeftLeg_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_5/LHipRoll
    - nao_5/LHipPitch
    - nao_5/LKneePitch
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_5/LHipRoll: {trajectory: 0.3, goal: 0.1}
    nao_5/LHipPitch: {trajectory: 0.3, goal: 0.1}
    nao_5/LKneePitch: {trajectory: 0.3, goal: 0.1}

RightLeg_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_5/RHipRoll
    - nao_5/RHipPitch
    - nao_5/RKneePitch
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_5/RHipRoll: {trajectory: 0.3, goal: 0.1}
    nao_5/RHipPitch: {trajectory: 0.3, goal: 0.1}
    nao_5/RKneePitch: {trajectory: 0.3, goal: 0.1}

LeftAnkle_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_5/LAnklePitch
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_5/LAnklePitch: {trajectory: 0.3, goal: 0.1}

RightAnkle_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_5/RAnklePitch
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_5/RAnklePitch: {trajectory: 0.3, goal: 0.1}

LeftFoot_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_5/LAnkleRoll
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_5/LAnkleRoll: {trajectory: 0.3, goal: 0.1}

RightFoot_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_5/RAnkleRoll
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_5/RAnkleRoll: {trajectory: 0.3, goal: 0.1}

LeftWheels_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
   - nao_5/left_wheel_joint_l
   - nao_5/left_wheel_joint_r
   - nao_5/front_left_wheel_joint_l
   - nao_5/front_left_wheel_joint_l

RightWheels_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
   - nao_5/right_wheel_joint_l
   - nao_5/right_wheel_joint_r
   - nao_5/front_right_wheel_joint_l
   - nao_5/front_right_wheel_joint_r


gazebo_ros_control:
    pid_gains:
      nao_5/HeadYaw: 
          p: 1000.0
          i: 100.0
          d: 1.0

      nao_5/HeadPitch:
          p: 1000.0
          i: 100.0
          d: 1.0

      nao_5/LShoulderPitch:
          p: 80.0
          i: 4.0
          d: 2.0

      nao_5/LElbowYaw:
          p: 100.0
          i: 100.0
          d: 0.0

      nao_5/LElbowRoll:
          p: 100.0
          i: 100.0
          d: 0.0

      nao_5/LShoulderRoll:
          p: 50.0
          i: 5.0
          d: 0.7

      nao_5/LWristYaw:
          p: 1.0
          i: 0.13
          d: 0.01

      nao_5/LHand:
          p: 0.0
          i: 0.0
          d: 0.0

      nao_5/RShoulderPitch:
          p: 80.0
          i: 4.0
          d: 2.0

      nao_5/RElbowYaw:
          p: 100.0
          i: 100.0
          d: 0.0

      nao_5/RElbowRoll:
          p: 100.0
          i: 100.0
          d: 0.0

      nao_5/RShoulderRoll:
          p: 50.0
          i: 5.0
          d: 0.7

      nao_5/RWristYaw:
          p: 1.0
          i: 0.13
          d: 0.01

      nao_5/RHand:
          p: 0.0
          i: 0.0
          d: 0.0

      nao_5/LHipYawPitch:
          p: 500.0
          i: 0.0
          d: 0.1

      nao_5/LHipRoll:
          p: 500.0
          i: 0.0
          d: 0.1

      nao_5/LHipPitch:
          p: 500.0
          i: 0.0
          d: 0.1

      nao_5/LKneePitch:
          p: 500.0
          i: 0.0
          d: 0.0

      nao_5/LAnklePitch:
          p: 500.0
          i: 0.0
          d: 0.0

      nao_5/LAnkleRoll:
          p: 500.0
          i: 0.0
          d: 0.0

      nao_5/left_wheel_joint_l:
          p: 0.0
          i: 0.0
          d: 0.0

      nao_5/left_wheel_joint_r:
          p: 0.0
          i: 0.0
          d: 0.0
        
      nao_5/right_wheel_joint_l:
          p: 0.0
          i: 0.0
          d: 0.0
        
      nao_5/right_wheel_joint_r:
          p: 0.0
          i: 0.0
          d: 0.0

      nao_5/RHipYawPitch:
          p: 500.0
          i: 0.0
          d: 0.1

      nao_5/RHipRoll:
          p: 500.0
          i: 0.0
          d: 0.1

      nao_5/RHipPitch:
          p: 500.0
          i: 0.0
          d: 0.1

      nao_5/RKneePitch:
          p: 500.0
          i: 0.0
          d: 0.0

      nao_5/RAnklePitch:
          p: 500.0
          i: 0.0
          d: 0.0

      nao_5/RAnkleRoll:
          p: 500.0
          i: 0.0
          d: 0.0
        
      nao_5/front_left_wheel_joint_l:
          p: 0.0
          i: 0.0
          d: 0.0

      nao_5/front_left_wheel_joint_r:
          p: 0.0
          i: 0.0
          d: 0.0

      nao_5/front_right_wheel_joint_l:
          p: 0.0
          i: 0.0
          d: 0.0

      nao_5/front_right_wheel_joint_r:
          p: 0.0
          i: 0.0
          d: 0.0
