  # Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  

  # Controllers ------------------------------------------------
Head_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_1/HeadYaw
    - nao_1/HeadPitch
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0

LeftArm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_1/LShoulderPitch
    - nao_1/LShoulderRoll
    - nao_1/LElbowYaw
    - nao_1/LElbowRoll
    - nao_1/LWristYaw
  constraints:
    goal_time: 0.8
    stopped_velocity_tolerance: 0
    nao_1/LShoulderPitch: {trajectory: 0.1, goal: 0.1}
    nao_1/LShoulderRoll: {trajectory: 0.3, goal: 0.2}
    nao_1/LElbowYaw: {trajectory: 0.2, goal: 0.1}
    nao_1/LElbowRoll: {trajectory: 0.3, goal: 0.1}
    nao_1/LWristYaw: {trajectory: 0.1, goal: 0.1}

RightArm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_1/RShoulderPitch
    - nao_1/RShoulderRoll
    - nao_1/RElbowYaw
    - nao_1/RElbowRoll
    - nao_1/RWristYaw
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_1/RShoulderPitch: {trajectory: 0.3, goal: 0.1}
    nao_1/RShoulderRoll: {trajectory: 0.3, goal: 0.2}
    nao_1/RElbowYaw: {trajectory: 0.3, goal: 0.1}
    nao_1/RElbowRoll: {trajectory: 0.5, goal: 0.2}
    nao_1/RWristYaw: {trajectory: 0.5, goal: 0.2}

LeftHand_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_1/LHand
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_1/LHand: {trajectory: 0.3, goal: 0.1}

RightHand_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_1/RHand
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_1/RHand: {trajectory: 0.3, goal: 0.1}

Pelvis_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_1/LHipYawPitch
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_1/LHipYawPitch: {trajectory: 0.3, goal: 0.1}

LeftLeg_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_1/LHipRoll
    - nao_1/LHipPitch
    - nao_1/LKneePitch
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_1/LHipRoll: {trajectory: 0.3, goal: 0.1}
    nao_1/LHipPitch: {trajectory: 0.3, goal: 0.1}
    nao_1/LKneePitch: {trajectory: 0.3, goal: 0.1}

RightLeg_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_1/RHipRoll
    - nao_1/RHipPitch
    - nao_1/RKneePitch
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_1/RHipRoll: {trajectory: 0.3, goal: 0.1}
    nao_1/RHipPitch: {trajectory: 0.3, goal: 0.1}
    nao_1/RKneePitch: {trajectory: 0.3, goal: 0.1}

LeftAnkle_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_1/LAnklePitch
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_1/LAnklePitch: {trajectory: 0.3, goal: 0.1}

RightAnkle_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_1/RAnklePitch
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_1/RAnklePitch: {trajectory: 0.3, goal: 0.1}

LeftFoot_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_1/LAnkleRoll
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_1/LAnkleRoll: {trajectory: 0.3, goal: 0.1}

RightFoot_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - nao_1/RAnkleRoll
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    nao_1/RAnkleRoll: {trajectory: 0.3, goal: 0.1}

LeftWheels_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
   - nao_1/left_wheel_joint_l
   - nao_1/left_wheel_joint_r
   - nao_1/front_left_wheel_joint_l
   - nao_1/front_left_wheel_joint_l

RightWheels_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
   - nao_1/right_wheel_joint_l
   - nao_1/right_wheel_joint_r
   - nao_1/front_right_wheel_joint_l
   - nao_1/front_right_wheel_joint_r


gazebo_ros_control:
    pid_gains:
      nao_1/HeadYaw: 
          p: 1000.0
          i: 100.0
          d: 1.0

      nao_1/HeadPitch:
          p: 1000.0
          i: 100.0
          d: 1.0

      nao_1/LShoulderPitch:
          p: 80.0
          i: 4.0
          d: 2.0

      nao_1/LElbowYaw:
          p: 100.0
          i: 100.0
          d: 0.0

      nao_1/LElbowRoll:
          p: 100.0
          i: 100.0
          d: 0.0

      nao_1/LShoulderRoll:
          p: 50.0
          i: 5.0
          d: 0.7

      nao_1/LWristYaw:
          p: 1.0
          i: 0.13
          d: 0.01

      nao_1/LHand:
          p: 0.0
          i: 0.0
          d: 0.0

      nao_1/RShoulderPitch:
          p: 80.0
          i: 4.0
          d: 2.0

      nao_1/RElbowYaw:
          p: 100.0
          i: 100.0
          d: 0.0

      nao_1/RElbowRoll:
          p: 100.0
          i: 100.0
          d: 0.0

      nao_1/RShoulderRoll:
          p: 50.0
          i: 5.0
          d: 0.7

      nao_1/RWristYaw:
          p: 1.0
          i: 0.13
          d: 0.01

      nao_1/RHand:
          p: 0.0
          i: 0.0
          d: 0.0

      nao_1/LHipYawPitch:
          p: 500.0
          i: 0.0
          d: 0.1

      nao_1/LHipRoll:
          p: 500.0
          i: 0.0
          d: 0.1

      nao_1/LHipPitch:
          p: 500.0
          i: 0.0
          d: 0.1

      nao_1/LKneePitch:
          p: 500.0
          i: 0.0
          d: 0.0

      nao_1/LAnklePitch:
          p: 500.0
          i: 0.0
          d: 0.0

      nao_1/LAnkleRoll:
          p: 500.0
          i: 0.0
          d: 0.0

      nao_1/left_wheel_joint_l:
          p: 0.0
          i: 0.0
          d: 0.0

      nao_1/left_wheel_joint_r:
          p: 0.0
          i: 0.0
          d: 0.0
        
      nao_1/right_wheel_joint_l:
          p: 0.0
          i: 0.0
          d: 0.0
        
      nao_1/right_wheel_joint_r:
          p: 0.0
          i: 0.0
          d: 0.0

      nao_1/RHipYawPitch:
          p: 500.0
          i: 0.0
          d: 0.1

      nao_1/RHipRoll:
          p: 500.0
          i: 0.0
          d: 0.1

      nao_1/RHipPitch:
          p: 500.0
          i: 0.0
          d: 0.1

      nao_1/RKneePitch:
          p: 500.0
          i: 0.0
          d: 0.0

      nao_1/RAnklePitch:
          p: 500.0
          i: 0.0
          d: 0.0

      nao_1/RAnkleRoll:
          p: 500.0
          i: 0.0
          d: 0.0
        
      nao_1/front_left_wheel_joint_l:
          p: 0.0
          i: 0.0
          d: 0.0

      nao_1/front_left_wheel_joint_r:
          p: 0.0
          i: 0.0
          d: 0.0

      nao_1/front_right_wheel_joint_l:
          p: 0.0
          i: 0.0
          d: 0.0

      nao_1/front_right_wheel_joint_r:
          p: 0.0
          i: 0.0
          d: 0.0
